import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

type FormData = {
  _id: string;
  projectName: string;
  projectURL: string;
  projectCategory: string;
  projectDetails: string;
  workers: number;
  productLaunch: string;
  email: string;
};

type HomeProps = {
  projects: FormData[];
};

export default function Home({ projects }: HomeProps) {
  return (
    <>
      <Head>
        <title>Multi Stepper Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul>
          {projects &&
            projects.map((project, idx) => (
              <li style={{ color: 'white' }} key={idx}>
                {project._id}
              </li>
            ))}
        </ul>
        <Link href={'/test'}>Test</Link>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const response = await fetch(`http://localhost:3000/api/projects`, {
      method: 'GET',
    });
    const data = await response.json();

    return {
      props: {
        projects: data,
      },
    };
  } catch (error) {
    console.error('Fetch Error', error);
    return {
      props: {
        data: [],
      },
    };
  }
}
