import Head from 'next/head';

import CreateProject from '@/components/screens/create-project/CreateProject';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function CreateProjectPage() {
  return (
    <>
      <Head>
        <title>Create Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <CreateProject />
      </main>
    </>
  );
}
